- name: Build React app
  run: npm run build

- name: Copy build folder to Azure VM
  uses: appleboy/scp-action@v0.1.7
  with:
    host: 172.206.82.46
    username: azureuser
    key: ${{ secrets.AZURE_PRIVATE_KEY }}
    source: "dist/*"          # <-- use dist instead of build
    target: "/home/azureuser/adil_docker"
